config/routes.rb
Rails.application.routes.draw do

  root 'boards#index'

  devise_for :users

  resources :boards do 
    resources :pins
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :pins, dependent: :destroy
  belongs_to :user

  validates :title, presence: true

  extend FriendlyId
  friendly_id :title, use: [:slugged,:finders]

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :board

  mount_uploader :image, ImageUploader

  paginates_per 5


  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :boards
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :description)
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :set_board

  # GET /pins
  # GET /pins.json
  def index
      @pins = @board.pins.order(:created_at).page(params[:page])
      respond_to do |format|
        format.html
        format.js
      end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.board_id = Board.friendly.find(@pin.board_id).id
    respond_to do |format|
      if @pin.save
        format.html { redirect_to board_pin_url(@board.slug,@pin.slug), notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to board_pin_path(@board.slug,@pin.slug), notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to board_pins_path(@board.slug), notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.friendly.find(params[:id])
    end

    def set_board
      @board = Board.friendly.find(params[:board_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:name, :image,:image_cache, :board_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/boards/_form.html.haml
= form_for @board, html: { class: "form form-horizontal board" } do |f|
  .form-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, class: 'form-control', required: true
    = error_span(@board[:title])
  .form-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_field :description, class: 'form-control', required: true
    = error_span(@board[:description])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), boards_path, :class => 'btn btn-default'

app/views/boards/edit.html.haml
- model_class = Board
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/boards/index.html.haml
- model_class = Board
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @boards.each do |board|
      %tr
        %td= link_to board.title, board_pins_path(board.slug)
        %td= board.description
        %td=l board.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_board_path(board), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), board_path(board), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_board_path, :class => 'btn btn-primary'

app/views/boards/new.html.haml
- model_class = Board
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/boards/show.html.haml
- model_class = Board
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @board.title
%p
  %strong= model_class.human_attribute_name(:slug) + ':'
  %br
  = @board.slug
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @board.description


= link_to t('.back', :default => t("helpers.links.back")), boards_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_board_path(@board), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), board_path(@board), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Pinterest"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Pinterest
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to t('Boards'), boards_path
            %li= link_to "Link 2", "/path2"
            %li= link_to "Link 3", "/path3"
            %li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          /= bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
      %footer
        %p &copy; Company 2014

app/views/pins/_form.html.haml
= form_for [@board,@pin], html: { class: "form form-horizontal pin" } do |f|

  .form-group
    = f.label :board, class: 'control-label'
    .controls
      = f.collection_select :board_id,Board.all, :id, :title
    = error_span(@pin[:board_id])
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@pin[:name])
  .form-group
    = f.label :image, class: 'control-label'
    .controls
      = f.file_field :image#, class: 'form-control', required: true
    = error_span(@pin[:image])
  =f.hidden_field :image_cache
  / .form-group
  /   = f.label :board_id, class: 'control-label'
  /   .controls
  /     = f.text_field :board_id, class: 'form-control', required: true
  /   = error_span(@pin[:board_id])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), board_pins_path(@board), :class => 'btn btn-default'

app/views/pins/_pin.html.haml
%tr.post
  %td= link_to pin.id, board_pin_path(@board.id,pin)
  %td= pin.name
  %td= link_to(image_tag(pin.image.thumb.url),board_pin_path(@board,pin))
  %td= pin.board.title
  %td=l pin.created_at
  %td
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_board_pin_path(@board,pin), :class => 'btn btn-default btn-xs'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), board_pin_path(pin,@board), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/pins/edit.html.haml
- model_class = Pin
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/pins/index.html.haml
- model_class = Pin
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped#posts
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:image)
      %th= model_class.human_attribute_name(:board)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody.page
    - @pins.each do |pin|
      =render pin


= link_to t('.new', :default => t("helpers.links.new")), new_board_pin_path(@board), :class => 'btn btn-primary'

= paginate @pins

app/views/pins/index.js.erb
$("#posts").append("<div class='page'><%= escape_javascript(render(@pins)) %></div>");

app/views/pins/new.html.haml
- model_class = Pin
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/pins/show.html.haml
- model_class = Pin
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @pin.name
%p
  %strong= model_class.human_attribute_name(:slug) + ':'
  %br
  = @pin.slug
%p
  %strong= model_class.human_attribute_name(:image) + ':'
  %br
  =image_tag @pin.image.normal.url, class: 'thumb'
  /= @pin.image
%p
  %strong= model_class.human_attribute_name(:board_id) + ':'
  %br
  = @pin.board.title


= link_to t('.back', :default => t("helpers.links.back")), board_pins_path(@board), :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_board_pin_path(@board,@pin), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), board_pin_path(@board,@pin), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'